### ISSUE TITLE
Delay when pressing Space in the game

### ISSUE THREAD

**Issue by iZuminnnn** [Manuteaa/dbd_autoSkillCheck#10]
![image](https://github.com/user-attachments/assets/68b47cc6-e250-4210-a3a8-606ddc959405)

I am experiencing a delay when pressing the Space key. The last skill check frame is correct, but in the actual game, there is a delay before the Space key is registered. I am unsure where the issue lies. My FPS is 60.

**Comment by Manuteaa** [comment]
Hello ! This latency is expected and is mainly due to ping, so no worries, this is well handled by the script :) 

From the REAME file that I just edited, for more clarity : 

> We experimentally made the conclusion that following the type of the skill check, we must hit the space bar a bit before the cursor reaches the great area, in order to anticipate the game input processing latency. That's why we have this dataset structure and granularity (with ante-frontier and frontier areas recognition).

> The last hit skill check frame : last frame (center-cropped image with size 224x224) the AI model triggered the SPACE bar. This may not be the actual hit frame (as registered by the game) because of game latency (such as ping). The AI model anticipates the latency, and hits the space bar a little bit before the cursor reaches the great area, that's why the displayed frame will always be few frames before actual game hit frame

**Comment by iZuminnnn** [comment]
@Manuteaa Thanks for the reply. I have a suggestion for you. I encountered a situation where my CPU was constantly at 100%, so I tried using CUDA GPU for onnxruntime, and it seems to work well. Example:
 ```
# Trained model with GPU support
import onnxruntime as ort 
...
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']  # Specify GPU provider
self.ort_session = ort.InferenceSession(onnx_filepath, providers=providers)
```

**Comment by Manuteaa** [comment]
Thanks for the nice suggestion, I will definitively add it as a new option !

Don't hesitate to reach me on discord if you are interested in contributing to the project, or to discuss about new features / new models (for killer side for example) as a side project.

**Comment by iZuminnnn** [comment]
@Manuteaa I got 60 ping, is it enough?

**Comment by Manuteaa** [comment]
I don't know, does it miss the great skill checks with your ping ? 

I would say 60 is fine, but maybe sometimes it can hit good instead of great for the tiny great area of repair/heal skill checks. No problem for others, they have a much bigger "great" area.

**Comment by VoidEyeCreator** [comment]
> Hello ! This latency is expected and is mainly due to ping, so no worries, this is well handled by the script :)
> 
> From the REAME file that I just edited, for more clarity :
> 
> > We experimentally made the conclusion that following the type of the skill check, we must hit the space bar a bit before the cursor reaches the great area, in order to anticipate the game input processing latency. That's why we have this dataset structure and granularity (with ante-frontier and frontier areas recognition).
> 
> > The last hit skill check frame : last frame (center-cropped image with size 224x224) the AI model triggered the SPACE bar. This may not be the actual hit frame (as registered by the game) because of game latency (such as ping). The AI model anticipates the latency, and hits the space bar a little bit before the cursor reaches the great area, that's why the displayed frame will always be few frames before actual game hit frame

This prediction delay can sometimes cause the model to press the space bar before the pointer reaches the “perfect” area and cause the skill check to fail, my fps is 120-130.

**Comment by Manuteaa** [comment]
You can : 
- Disable the ante-frontier hit (best option) : edit `dbd/AI_model.py ` l.13 `2: {"desc": "repair-heal (ante-frontier)", "hit": False}`
- Reduce your fps ;)

**Comment by VoidEyeCreator** [comment]
> You can :
> 
> * Disable the ante-frontier hit (best option) : edit `dbd/AI_model.py ` l.13 `2: {"desc": "repair-heal (ante-frontier)", "hit": False}`
> * Reduce your fps ;)

The problem has been solved, thanks!

**Comment by iZuminnnn** [comment]
The problem solved by turn off vsync, tks @Manuteaa
