### ISSUE TITLE
Use with hyperfocus

### ISSUE THREAD

**Issue by Manuteaa** [Manuteaa/dbd_autoSkillCheck#11]
Hello, can someone with the perk hyperfocus tell me if it works well ? thanks

**Comment by iZuminnnn** [comment]
I'm use it, it works very well

**Comment by Manuteaa** [comment]
nice, thanks !

**Comment by VariedOblivious** [comment]
Pretty good, getting about 95% ish...  Concerningly I am getting 100% CPU spikes when running... any ideas?

**Comment by Manuteaa** [comment]
You can run it using your gpu if you prefer
