### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by S0nna** [Manuteaa/dbd_autoSkillCheck#14]
Running run_monitoring_gradio.py opens a powershell window briefly then closes it, that's it

**Comment by Manuteaa** [comment]
Did you follow the execution instructions ? Maybe you missed something like installing gradio (gradio runs a local web server, maybe starting this powershell window and failing). 
Can you try again following the instructions then send me the console logs if there is still a bug ?

**Comment by S0nna** [comment]
Yeah sorry! This was an issue with something else unrelated to the auto skill check that was affecting it. Sorry!
