### ISSUE TITLE
It doest work, why?

### ISSUE THREAD

**Issue by allmyfdisgay** [Manuteaa/dbd_autoSkillCheck#15]
[
![6cb2e57131ea64d2fe4abc7f3ab5ee1d](https://github.com/user-attachments/assets/0b639990-5f1d-4ef9-b225-c6ba6b4902e4)
](url)
![560ae7c3dc278b3069d612993a101f12](https://github.com/user-attachments/assets/aa197d89-c4aa-425a-b9fb-1fe29916e06e)
![b899ee6ee4cedacc5ebe32915321744c](https://github.com/user-attachments/assets/1a1c1ecf-d534-4f5e-b9c7-76d7942d1970)
everything seems fine here

**Comment by Manuteaa** [comment]
Hello, you just need to read correctly the README file, you ran the wrong script

**Comment by SouthernFrenzy** [comment]
Bro, i created a created env, installed prerequisites, git cloned and enabled public link. Yet when i ran the script and played the game it doesn't work. Could you please explain what i did wrong? I have read the read me.

**Comment by hemlock12** [comment]
You need to run 'run_monitoring_gradio.py' (not 'run_single_pred_gradio.py')

**Comment by allmyfdisgay** [comment]
I did run the run_monitoring_gradio.py bro,it didt work!so I tried the single one for test as the readme says

**Comment by Manuteaa** [comment]
Did you check this from the FAQ;

**Why does the script do nothing ?**
- Check if the AI model monitors correctly your game: set the debug option of the webui to "display the monitored frame". Play the game and check if it displays correctly the skill check
- Check if you have no error in the python console logs
- Check if your game settings are not unusual (such as special resolution or game filters): your displayed images "last hit skill check frame" should be similar with the ones in my examples

Especially the last point, the skill check in your screenshot seems small, can you check your resolutions settings ? It should be 100% for all settings related to resolution/scaling

**Comment by allmyfdisgay** [comment]
it didt show the monitored frame
![Uploading 41b3f71c749896d132ae3a26b9850657.png…]()

**Comment by SouthernFrenzy** [comment]
I had even asked my friend who does IT to assist me and neither of us could crack it to get it working. We are both completely baffled and we followed all within the Read me.  

What are we missing?
Maybe you can help us on discord or something or better yet, make a video showing us how you did it from 0-100

**Comment by Manuteaa** [comment]
Check the first point I mentioned, you have a debug option to show all the monitored frames (no AI is involved, it does not detect skill checks, but it does just show a crop of your main screen). Can you see the frames ?

**Comment by SouthernFrenzy** [comment]
brother, i don't even know how to use python. Without my friend i wouldn't have gotten even to this point. This is why, i ask you kindly, could you do a video. I really want to use it but i am lvl 0. Unless you make an EXE directly i am useless.

**Comment by VimeRXXL1** [comment]
Hi, where can I download exe file?

**Comment by VimeRXXL1** [comment]
> > Hi, where can I download exe file?
> 
> There is no .exe currently. OP said they would create it but i have scanned his read me and such. NO sign of it. WE wait.

Oke, thx

**Comment by Manuteaa** [comment]
Try this https://github.com/Manuteaa/dbd_autoSkillCheck/releases/tag/v1.0

**Comment by VimeRXXL1** [comment]
> Try this https://github.com/Manuteaa/dbd_autoSkillCheck/releases/tag/v1.0

Thx is it safe ?>

**Comment by SouthernFrenzy** [comment]
im testing now and i have an i9 13k and a 4080 rog. I am getting the skill checks too early. Let it be 1 normal skill 1 failed and it rotates. Kindly tell me what i am doing wrong?

I want them great - 300xp

**Comment by Manuteaa** [comment]
> Thx <З Is it safe ?>

Yes



> 1/4 times it works the rest they are premature failed checks.

I wrote a fix for this in the README: `Edit the file dbd/AI_model.py to disable the ante-frontier hits (set hit variable to False, for example 2: {"desc": "repair-heal (ante-frontier)", "hit": False})`

But since you use the standalone app you cannot edit the file. I have to add the fix as an option in the web app. Will do it later

**Comment by SouthernFrenzy** [comment]
Please, if you could that would be amazing !

It would make my Christmas if you could get it working and always hitting great (300)

**Comment by Manuteaa** [comment]
https://github.com/Manuteaa/dbd_autoSkillCheck/releases/tag/v1.1

**Comment by SouthernFrenzy** [comment]
ill check in a bit when i get home. Thank you brother!
Ill give you my feedback the moment i have tested

**Comment by VimeRXXL1** [comment]
> https://github.com/Manuteaa/dbd_autoSkillCheck/releases/tag/v1.1

Hi, I tried it and everything works as it should! Thank you for your hard work

**Comment by Manuteaa** [comment]
Nice 🎉 Thanks for the feedback.

If you found this project helpful, you can give it a ⭐ on GitHub. Starring helps others discover the project and shows support for the work put into it 😄

**Comment by SouthernFrenzy** [comment]
Trying it out now,
exciting to see someone got it working./

WISH ME LUCK!

**Comment by SouthernFrenzy** [comment]
Man, im still not able to get it consistent. What am i doing wrong?

Full screen, all set to native resolution of screen. Debug, untick AntiFrontier. 
By the way, i don't get the info on the right 'skill check recog'. but i highlighted the great skill 60%.

and im still not getting perfect hits every time. also, if there is a fast QTE it goes early again.

Im soo defeated, what am i doing wrong?!

**Comment by VimeRXXL1** [comment]
> Man, im still not able to get it consistent. What am i doing wrong?
> 
> Full screen, all set to native resolution of screen. Debug, untick AntiFrontier. By the way, i don't get the info on the right 'skill check recog'. but i highlighted the great skill 60%.
> 
> and im still not getting perfect hits every time. also, if there is a fast QTE it goes early again.
> 
> Im soo defeated, what am i doing wrong?!

![{4C27CDC8-5337-47D4-9702-034234CED32D}](https://github.com/user-attachments/assets/efc8fae5-8e3f-4266-8baa-b33ff8f64186)
This is my options and its work great!

**Comment by SouthernFrenzy** [comment]
ahh, so you have debug off;. In game, what are your options could u kindly tell me?

**Comment by VimeRXXL1** [comment]
> ahh, so you have debug off;. In game, what are your options could u kindly tell me?

Try disabling debug

**Comment by VimeRXXL1** [comment]
I have standard settings in the game

**Comment by SouthernFrenzy** [comment]
i just got 3 (300/great) and 1 explosion. I seems to either be getting the explosions on super quick events or random after a couple aced ones.

Default in game, window fullscreen , 4k and fps set to 120.

How are you not getting any explosions?

**Comment by SouthernFrenzy** [comment]
<img width="620" alt="Screenshot 2024-12-15 184553" src="https://github.com/user-attachments/assets/d26ffe12-ed8c-4c38-aac2-48b58a19ceb5" />

As you can see my fps is fine for the program.

**Comment by VimeRXXL1** [comment]
> <img alt="Screenshot 2024-12-15 184553" width="620" src="https://private-user-images.githubusercontent.com/191010442/395885899-d26ffe12-ed8c-4c38-aac2-48b58a19ceb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODkxNzMsIm5iZiI6MTczNDI4ODg3MywicGF0aCI6Ii8xOTEwMTA0NDIvMzk1ODg1ODk5LWQyNmZmZTEyLWVkOGMtNGMzOC1hYWMyLTQ4YjU4YTE5Y2ViNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxODU0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmE4NjUzZjBmOTYyMzM3MjY4ZjUwMzczYzY3NjQ3OThkN2NlZDA3YzM5OTM4NGQwN2E5OTY2NjM1NmEzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UZFAZ-n337VTQtTkp8-v7gquFwtTLp-HuPU9SZ30Cz8">
> As you can see my fps is fine for the program.

try reinstalling the files. Delete the old folder and download the new one

**Comment by Manuteaa** [comment]
The AI will never hit 100% great.
- If it mostly hit too early: uncheck the last box (ante-frontier hits)
- If it mostly hit normal: keep the option checked, check your game settings like Vsync & resolution / scales
- If it does nothing: check the FAQ

If you have some great but some normal, maybe it's just your ping, or the AI FPS drops when it runs in background. Try running it in admin mode

**Comment by VimeRXXL1** [comment]
> The AI will never hit 100% great.
> 
> * If it mostly hit too early: uncheck the last box (ante-frontier hits)
> * If it mostly hit normal: keep the option checked, check your game settings like Vsync & resolution / scales
> * If it does nothing: check the FAQ
> 
> If you have some great but some normal, maybe it's just your ping, or the AI FPS drops when it runs in background. Try running it in admin mode

I'll agree.

**Comment by SouthernFrenzy** [comment]
im running it in admin mode and will get back to you.

**Comment by SouthernFrenzy** [comment]
so, my fps on the web thing is over 100 constantly..

3 great, 1 normal 3 failed one after another.

I swear, its driving me F* nuts. I did everything right, settings and all. yet its a pattern.

**Comment by SouthernFrenzy** [comment]
just had 3 in a row that were 300.. 
I don't get what causes the premature fails.

on the right, there the names and percentages are. Am i suppose to highlight or flag something?

**Comment by Manuteaa** [comment]
No, there is nothing to do in the webui, except uncheck the box in your case.

Mhh, that's weird, maybe try capping your game FPS to 60

**Comment by SouthernFrenzy** [comment]
no bro, my fps is uncapped the whole time.  The game is running at 120fps in game. I can see it on MSI or within the web api
My screen is a 60hz one yes, but my fps is 100% set to 120

**Comment by SouthernFrenzy** [comment]
im using miscrosoft edge. does that matter?

**Comment by Manuteaa** [comment]
- cap your game fps at 60 (in DBD settings), no more
- disable vsync, frame generation etc in dbd settings (and your monitor?)
- don't worry, don't get a heart attack

**Comment by SouthernFrenzy** [comment]
i did that, same dam result. 

Nothing is changing.

Its the Webapi that is dropping for some reason.

Ye man, i know but i want it to work. dammit 
>:(

**Comment by Manuteaa** [comment]
You mean the AI model FPS (value on the Web UI) are dropping when you play ?
Do you have multiple monitors ? If this is the case, can you set the game in "Windowed fullscreen". Then you start the .exe in admin, you place the web ui on your second monitor and check the FPS while you play?

If it still not works, can you contact me on discord instead? thanks

**Comment by Manuteaa** [comment]
You mean the AI model FPS (value on the Web UI) are dropping when you play ?
Do you have multiple monitors ? If this is the case, can you set the game in "Windowed fullscreen". Then you start the .exe in admin, you place the web ui on your second monitor and check the FPS while you play?

If it still not works, can you contact me on discord instead? thanks

**Comment by Manuteaa** [comment]
I sent you the discord link

**Comment by Manuteaa** [comment]
OP solved the problem by changing its monitor resolution in windows settings. The script does not seem to handle 4K.

**Comment by Manuteaa** [comment]
OP solved the problem by changing its monitor resolution in windows settings. The script does not seem to handle 4K.
