### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by quirxsama** [Manuteaa/dbd_autoSkillCheck#16]
We need a linux support or alternative. Is it planned ?

**Comment by hemlock12** [comment]
> We need a linux support or alternative. Is it planned ?

Hi, can you try to replace dbd_autoSkillCheck-main/dbd/utils/directkeys.py contents to:
`from pynput import keyboard
import time

# Create a controller to send keyboard inputs
controller = keyboard.Controller()

# Key definitions
UP = keyboard.Key.up
DOWN = keyboard.Key.down
SPACE = keyboard.Key.space

# Functions

def PressKey(key):
    controller.press(key)

def ReleaseKey(key):
    controller.release(key)

if __name__ == "__main__":
    PressKey(SPACE)
    time.sleep(0.5)
    ReleaseKey(SPACE)
    print("Pressed")`
Let me know, if it works.

**Comment by quirxsama** [comment]
Should I change all the file or just specified part?

**Comment by hemlock12** [comment]
Replace whole file with this code

**Comment by quirxsama** [comment]
I deleted the game so I will reinstall it i will answer you this evening. I didnt get any error messages and I have 200 ai fps but I dont have game installed so I cant test.

**Comment by quirxsama** [comment]
I just tested it now, my AI FPS is between 80 - 100 and my game FPS is 90 but it still has a high latency that can hit good in the middle of skill checks. I didnt see any great

**Comment by quirxsama** [comment]
Maybe if I use a GPU, it'll be fine but how

**Comment by hemlock12** [comment]
That's strange; for me, it performs great even on the CPU. To use the GPU, you'll need to install cuDNN and CUDA (if you're using NVIDIA). You can check the required dependencies in the terminal when you try running it on the GPU. Just to confirm, you're using X, correct?

**Comment by quirxsama** [comment]
Yes its X11 also I have R5 3600 and RTX2060. Maybe it is the reason?

**Comment by quirxsama** [comment]
I tried gpu now, I had more AI Fps and Game fps but nothing changed its late anyway

**Comment by quirxsama** [comment]
![resim](https://github.com/user-attachments/assets/bc8961b0-a0a7-42e3-b17e-1399be2b6da9)
Here is last skill check

**Comment by quirxsama** [comment]
I think pynput is slow for it but you know better

**Comment by hemlock12** [comment]
I don't know better, but it just works for me, you can try other libraries, sorry

**Comment by quirxsama** [comment]
I fixed with changing pynput to evdev. If someone else encounters the same problem, they can fix it by replacing this code with directkeys.py.

```
from evdev import UInput, ecodes

# Kullanıcı girişi başlat
ui = UInput()

# Tuş haritaları (evdev kodları)
SPACE = ecodes.KEY_SPACE
UP = ecodes.KEY_UP
DOWN = ecodes.KEY_DOWN

def PressKey(key):
    """Tuşa bas."""
    ui.write(ecodes.EV_KEY, key, 1)  # 1: Press
    ui.syn()

def ReleaseKey(key):
    """Tuşu bırak."""
    ui.write(ecodes.EV_KEY, key, 0)  # 0: Release
    ui.syn()

# Uygulama kapanırken temizlik yap
import atexit
atexit.register(ui.close)

```
