### ISSUE TITLE
Question about the Programm

### ISSUE THREAD

**Issue by Maxi2200227** [Manuteaa/dbd_autoSkillCheck#4]
I was thinking about using the script, but my question now is how high the ban rate is with Python or generally scripts that automate actions, specifically in Dead by Daylight.

**Comment by Manuteaa** [comment]
Hello, not sure about how the anticheat system works. The script automatically press the space bar using this https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes?redirectedfrom=MSDN but at a very slow rate (max 1hit/s)

Maybe worth checking if it can trigger the anticheat system... Never had any problem in my account
