### ISSUE TITLE
Regarding the status of the project

### ISSUE THREAD

**Issue by Pazdikan** [Manuteaa/dbd_autoSkillCheck#5]
In the last paragraph of the readme, you mention a possible solution for missing great skill checks. I understand that this is more of a study, but will you try to implement that?

Thank you for this project, it’s very helpful 😁

**Comment by Manuteaa** [comment]
Hello 😁
The answer is in this thread https://github.com/Manuteaa/dbd_autoSkillCheck/issues/2#issuecomment-2254473915
