### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by AbusedPet** [Manuteaa/dbd_autoSkillCheck#7]
Not sure if I'm doing something wrong, I've installed everything and I'm running the run.py it say's "Monitoring the screen" and I played a couple games with it running in the background but it doesn't seem to be doing anything on any type of skill check?

**Comment by Manuteaa** [comment]
Hello, maybe you use multiple screens and it monitors the wrong one ?
Check if you play on the main screen. You can also edit the lines 40 and 41 of `run.py ` to help you find why it does not work (set both variables to True)

**Comment by AbusedPet** [comment]
It's giving me this as an error: "\dbd_autoSkillCheck-main\run.py:29: RuntimeWarning: invalid value encountered in divide
  img = img / 255.0"
  
  Do I try changing it?

**Comment by Manuteaa** [comment]
Can you pull, set both variables to `True` then check if you have a new error and/or if there is an image saved in `saved_images/monitored_image.png` ?

Maybe there is an issue when capturing screenshots of your main screen

**Comment by AbusedPet** [comment]
Nope, no new error and there is saved images. No idea what is wrong

**Comment by Manuteaa** [comment]
Which version of python do you use ?
Can you add this debug line after l.27 : `print(img.shape, img[0,0])`

the code should be like that : 
```
img = np.array(screenshot, dtype=np.float32)
print(img.shape, img[0,0])
img = np.flip(img[:, :, :3], 2)
```

And send me the logs on your console please
I have something like that 
```
Monitoring the screen...
(224, 224, 4) [ 34.  31.  30. 255.]
(224, 224, 4) [ 34.  31.  30. 255.]
etc.
```

**Comment by Manuteaa** [comment]
Can you pull the new code and run it in game please ? then tell me the logs

```
Monitor crop settings : {'top': 428, 'left': 848, 'width': 224, 'height': 224}
Monitoring the screen...
Average fps: 71.4
Average fps: 76.7
Average fps: 65.7
```
