### ISSUE TITLE
Insta-Failing 

### ISSUE THREAD

**Issue by WhatsUp5** [Manuteaa/dbd_autoSkillCheck#8]
When the script is running, it instantly presses space when a skill check comes up, rather than being precise for a great skill check. This was tested on a dual monitor and a single monitor setup.

**Comment by Manuteaa** [comment]
Hello, can you set the debug line of the script `run.py` to `save_images=True` then send some saved frames please ?

**Comment by WhatsUp5** [comment]
![6](https://github.com/user-attachments/assets/3bc45ddf-a58d-482f-89c7-15d0a5b8b6fb)
![7](https://github.com/user-attachments/assets/a9ea6948-f83e-4044-8979-590428665c20)
![8](https://github.com/user-attachments/assets/580c936d-c99d-4e50-ae72-17166ef73523)
![0](https://github.com/user-attachments/assets/11188e10-74e8-4981-8525-447ac54c5fd1)
![1](https://github.com/user-attachments/assets/f66df6cb-e0ae-4062-9401-5872aff2b5cb)
![2](https://github.com/user-attachments/assets/79489b72-7c50-468e-88eb-0809d328157f)
![3](https://github.com/user-attachments/assets/5db560d6-45d4-4f0d-945d-7e714dcd9739)
![4](https://github.com/user-attachments/assets/1b35f7fb-2075-42c5-9fb9-0ec522bfb3f3)
![5](https://github.com/user-attachments/assets/99d1b65c-88b5-4a22-b225-6569f3c83e36)

For this test, I was using https://dbd.lucaservers.com/. Results were the same in the actual game, but much more inconvenient to have gone back in and recorded.

**Comment by WhatsUp5** [comment]
![6](https://github.com/user-attachments/assets/60e29043-337d-4ef7-b4e2-d2cc94e3ec4a)
![7](https://github.com/user-attachments/assets/657394e9-78f6-412b-b5cc-16b2377e7b1e)
![0](https://github.com/user-attachments/assets/9cc16d34-e19c-4cc2-b637-bed77b9631d6)
![1](https://github.com/user-attachments/assets/0c50bb5a-01be-476a-9a36-738f60365a3e)
![2](https://github.com/user-attachments/assets/0de3afde-8ee8-4858-a952-577f93a05658)
![3](https://github.com/user-attachments/assets/028c9bac-8d2d-408f-86dd-56bc63af7008)
![4](https://github.com/user-attachments/assets/8358449b-551b-43c0-9fd8-dd3938c85c8c)
![5](https://github.com/user-attachments/assets/5e2a9328-7acb-42a9-b85e-b29000305bcc)

These are real in-game screenshots. I failed to mention that it does mostly work for wiggling skill checks(which is interesting), but does not work for gen skill checks AT ALL.

**Comment by Manuteaa** [comment]
Look images in this folder https://github.com/Manuteaa/dbd_autoSkillCheck/tree/main/tests/data/1
Your monitored images should have similar resolution, which is not the case. Images corresponds to a center crop of size 224x224 at the middle of your main screen. Your images seems much more zoomed

Do you use game filters ? mods ? special resolution settings ?
Maybe try to modify your resolution setting to the default one and tell me if it is ok. If it does not work, can you tell me your screen resolution ? Your game resolution setting ?

**Comment by WhatsUp5** [comment]
Resolution is the problem. Could you share what resolution and other game settings you've been using with this?

**Comment by Manuteaa** [comment]
I use 3840x2160, maybe try the highest one available for you with similar aspect ratio ?

**Comment by WhatsUp5** [comment]
3840x2160 100% scaling in Windows settings. 3840x2160 in-game all 3 types tested,(Fullscreen, Windows Fullscreen, and windowed) now there's no response in-game, but it DOES respond flawlessly for the website??? I literally have no idea what the issue could be.

**Comment by WhatsUp5** [comment]
I'm using 3840x2160 in Windows set at 100%. I'm using 3840x2160 in-game, but the skill checks still insta-fail, no matter what settings I use it can't get the right crop for the AI model to work with. I'll need much more specific in-game and Windows settings.

**Comment by WhatsUp5** [comment]
![92](https://github.com/user-attachments/assets/517e9828-5e60-4a50-b3bc-20006353f3bc)
![93](https://github.com/user-attachments/assets/2fe2d855-d838-4f1f-9847-e13a48f342de)
![94](https://github.com/user-attachments/assets/3e2feea5-a8f7-40f6-994f-565fc91f68ff)
![91](https://github.com/user-attachments/assets/9ce5d784-f0c6-4ec6-b168-7335d65254d1)

I'm pretty sure I'm set once I find the right settings that bring down the skill check into the crop size

**Comment by Manuteaa** [comment]
- Windows : 1920x1080 (scale 100%)
- Game : 3840x2160

![image](https://github.com/user-attachments/assets/40820d8c-db65-48bb-8bf9-bad85333d7fb)
![image](https://github.com/user-attachments/assets/1c640086-673e-4577-979a-1eeabd13b9fc)

In game image : 
![image](https://github.com/user-attachments/assets/1e2edbbd-f83c-44f3-8232-e7e13889f787)


Can you pull the new code and run it in game please ? then tell me the logs
```
Monitor crop settings : {'top': 428, 'left': 848, 'width': 224, 'height': 224}
Monitoring the screen...
Average fps: 71.4
Average fps: 76.7
Average fps: 65.7
```
