### ISSUE TITLE
Hello, Couple questions

### ISSUE THREAD

**Issue by LtLunchbox** [Manuteaa/dbd_autoSkillCheck#9]
What platform did you test this thing on?
Can you list the specification of the PC you tested this on?
Thanks in advance!

**Comment by Manuteaa** [comment]
Hello ! Check the Executions instructions of the README file

> I have only tested the model on my own computer running Windows 11 with CUDA version 12.3
Create your own python env (I have python 3.11) and install the necessary libraries using the command : pip3 install numpy mss onnxruntime pyautogui IPython pillow
